require "./models"

# in this file we can make use of our ActiveRecord models to create starter data
User.create(username: "Catacylsm", password: "12345", birthday: "01/01/1980", first_name: "Cat", last_name: "Perry", email: "000.perry@gmail.com", userimage: "https://github.com/account")
User.create(username: "Laurenisnerdy", password: "12345", birthday: "01/01/1980", first_name: "Lauren", last_name: "Tracy", email: "ltabc@gmail.com", userimage: "https://avatars2.githubusercontent.com/u/37302245?s=400&v=4")
User.create(username: "LadyMada", password: "12345", birthday: "01/01/1980", first_name: "Mada", last_name: "Romero", email: "ladymada@gmail.com", userimage: "https://avatars0.githubusercontent.com/u/37271419?s=400&v=4")
User.create(username: "AlexRocks", password: "12345", birthday: "01/01/1980", first_name: "Alex", last_name: "Honnold", email: "alexrocks@gmail.com", userimage: "https://s7.postimg.cc/vi2ebkjff/climbing-yosemite-ropeless-380c4a23.jpg")
User.create(username: "Spock", password: "12345", birthday: "01/01/1980", first_name: "Mr", last_name: "Spock", email: "livelong@prosper.com", userimage: "https://s7.postimg.cc/usjlz7b63/spock.jpg")


Post.create(title: "The 10 Best Places in the World to Mountain Bike", author: "Cat Perry", content: "You haven't lived until you're flying down these singltracks. Travel colorful darn design traveler darn organized darn fun theme. Organized organized website colorful colorful, traveler webdesign darn pretty fun colorful. Organized whimsical theme simple modern webdesign, clean webdesign design cute adventure colorful traveler. Darn WordPress whimsical traveler clean website, theme modern pretty clean traveling adventure. Simple theme Travel colorful, traveling clean design adventure colorful traveler traveler expedition. Colorful adventure modern, excursion design modern modern website whimsical wanderlust", user_id: 1, images: "https://s7.postimg.cc/6q2s444qz/action-adventure-bicycle-71104.jpg")
Post.create(title: "Tips for Female Solo Travelers", author: "Cat Perry", content: "It's hard enough to know exactly where is safe while traveling wiht others, but to feel really free when traveling as a woman takes a few extra steps. Follow these 25 essential tips for solo travel and you're golden.", user_id: 1, images: "https://s7.postimg.cc/k4fv083q3/adrenaline-adventure-bali-863061.jpg")
Post.create(title: "4 Canals to See At Midnight", author: "Mada Romero", content: "When night falls on these four canals around the world you'll forget where you are for good.", user_id: 3, images: "https://s7.postimg.cc/vw3qb0qmj/architecture-boat-buildings-462329.jpg")
Post.create(title: "Helicopter Ride Over Lapland, Finland", author: "Mada Romero", content: "Finland colorful colorful, traveler webdesign darn pretty fun colorful. Organized whimsical theme simple modern webdesign, clean webdesign design cute adventure colorful traveler. Darn WordPress whimsical traveler clean website, theme modern pretty clean traveling adventure. Simple theme Travel colorful, traveling clean design ", user_id: 3, images: "https://s7.postimg.cc/q5djxcnsb/adventure-aerial-beautiful-351448.jpg")
Post.create(title: "How I Crushed My First Century Ride in Hawaii", author: "Cat Perry", content: "You can't imagine how riding past steaming volcanoes while completeing your first 100-mile ride can change your life.", user_id: 1, images: "https://s7.postimg.cc/ph4pep75n/action-bicycling-bike-287398.jpg")
Post.create(title: "My Fear of Heights Disappeared When I Tried Sky Diving. Here's how.", author: "Lauren Tracy", content: "Excursion travelblogger colorful pretty organized organized Travel. Whimsical simple cute darn, fun design adventure travelblogger clean simple webdesign clean. Website clean design Travel theme, website wanderlust simple design blogger fun theme. Theme colorful modern website fun excursion fun. Modern organized wanderlust, fun expedition Travel excursion clean website traveling.", user_id: 2, images: "https://s7.postimg.cc/al666x0u3/adventure-flares-formation-70361.jpg")
Post.create(title: "Look At Me I Travel", author: "Lauren Tracy", content: "Design clean website expedition wanderlust, organized design clean simple theme. Simple Travel adventure design expedition whimsical adventure, website website traveling clean design. Fun adventure adventure theme, modern fun website Travel design theme organized. Webdesign WordPress colorful expedition, Travel colorful darn design traveler darn organized darn fun theme. Organized organized website colorful colorful, traveler webdesign darn pretty fun colorful. Organized whimsical theme simple modern webdesign, clean webdesign design cute adventure colorful traveler. Darn WordPress whimsical traveler clean website, theme modern pretty clean traveling adventure. Simple theme Travel colorful, traveling clean design adventure colorful traveler traveler expedition. Colorful adventure modern, excursion design modern modern website whimsical wanderlust.", user_id: 2, images: "https://s7.postimg.cc/oeuivz157/arctic-aurora-aurora-borealis-258112.jpg")
Post.create(title: "Cheap Travel: Make It So. Now, Please.", author: "Lauren Tracy", content: "On my last trip to Iceland, where my wallet thinned out like never before, I wondered, how would Captain Picard navigate this expensive as hell country without going broke. So I'm channeling him.", user_id: 2, images: "https://s7.postimg.cc/oeuivz157/arctic-aurora-aurora-borealis-258112.jpg")
Post.create(title: "Ten Years of Hell, or How I Became a World-Class Free Climber", author: "Alex Honnold", content: "Webdesign WordPress colorful expedition, Travel colorful darn design traveler darn organized darn fun theme. Organized organized website colorful colorful, traveler webdesign darn pretty fun colorful. Organized whimsical theme simple modern webdesign, clean webdesign.", user_id: 4, images: "https://s7.postimg.cc/l7zzcc19n/alex-honnold-01.png")
Post.create(title: "All the Things: Why Training In Multiple Sports Can Take Your Main Sport to the Next Level.", author: "Alex Honnold", content: "Webdesign WordPress colorful expedition, Travel colorful darn design traveler darn organized darn fun theme. Organized organized website colorful colorful, traveler webdesign darn pretty fun colorful. Organized whimsical theme simple modern webdesign, clean webdesign.", user_id: 4, images: "https://s7.postimg.cc/7d1otnh2j/action-adventure-beach-390051.jpg")
Post.create(title: "20 Real Places With OtherWorldly Lanscadpes to See Before You Die", author: "Mr Spock", content: "Looking to explore new worlds? If you're an Epic Traveler like me you sure as heck are. And Guess what? I've been where you want to go. These 20 locales across earth look exactly like Mars, Venus and other planets far beyon dour solar system that I've been to, folks. If you can't get to Space, go here.", user_id: 5, images: "https://s7.postimg.cc/8glt5i6tn/adventure-alps-background-207195.jpg")